
/* Generated by RED (red/iss.py) from ISASpec "matrixmul_imac" — do not edit.
 *
 * One Spike extension holding every designed instruction. Each is a plain
 * R-type in a custom opcode slot: rs1 = &in[words], rs2 = &out[words], rd = 0.
 */
/* libstdc++'s <atomic_wait> reaches for SYS_futex, which spike's own build gets
   transitively; include it up front so this stands alone. */
#include <sys/syscall.h>

/* Every file that uses spike's register macros must first say whether register
   writes go into the commit log. Spike's own instruction bodies define it (0 in
   insn_template.cc, 1 in rocc.cc); 1 keeps --log-commits honest for our
   instructions too. */
#define DECODE_MACRO_USAGE_LOGGED 1

#include "extension.h"
#include "decode_macros.h"
#include "mmu.h"

#include <cstdint>
#include <cstring>
#include <vector>


/* ---- ISS model for imac_custom (3 x 32-bit words) ---- */
namespace red_imac_custom {
void imac_custom_iss(const uint32_t in[3], uint32_t out[3]) {
    uint32_t c = in[0];
    uint32_t a = in[1];
    uint32_t b = in[2];
    out[0] = c + (a * b);
    out[1] = 0;
    out[2] = 0;
}
}



static reg_t red_exec_imac_custom(processor_t* p, insn_t insn, reg_t pc)
{
  const reg_t src = RS1, dst = RS2;
  uint32_t in[3], out[3];

  for (int i = 0; i < 3; i++)
    in[i] = (uint32_t)MMU.load<uint32_t>(src + 4 * i);
  memset(out, 0, sizeof(out));

  red_imac_custom::imac_custom_iss(in, out);

  for (int i = 0; i < 3; i++)
    MMU.store<uint32_t>(dst + 4 * i, out[i]);

  WRITE_RD(0);
  return pc + 4;
}


class red_ext_t : public extension_t
{
 public:
  const char* name() const override { return "red"; }

  std::vector<insn_desc_t> get_instructions(const processor_t &) override {
    return {
      {0x0000000b, 0xfe00707f, red_exec_imac_custom, red_exec_imac_custom, red_exec_imac_custom, red_exec_imac_custom, red_exec_imac_custom, red_exec_imac_custom, red_exec_imac_custom, red_exec_imac_custom},
    };
  }

  std::vector<disasm_insn_t*> get_disasms(const processor_t *) override {
    return {
      new disasm_insn_t("imac_custom", 0x0000000b, 0xfe00707f, {}),
    };
  }
};

REGISTER_EXTENSION(red, []() { static red_ext_t ext; return &ext; })
