
/* Generated by RED (red/iss.py) from ISASpec "Float Matrix Multiply Extension" — do not edit.
 *
 * One Spike extension holding every designed instruction. Each is a plain
 * R-type in a custom opcode slot: rs1 = &in[words], rs2 = &out[words], rd = 0.
 */
/* libstdc++'s <atomic_wait> reaches for SYS_futex, which spike's own build gets
   transitively; include it up front so this stands alone. */
#include <sys/syscall.h>

/* Every file that uses spike's register macros must first say whether register
   writes go into the commit log. Spike's own instruction bodies define it (0 in
   insn_template.cc, 1 in rocc.cc); 1 keeps --log-commits honest for our
   instructions too. */
#define DECODE_MACRO_USAGE_LOGGED 1

#include "extension.h"
#include "decode_macros.h"
#include "mmu.h"

#include <cstdint>
#include <cstring>
#include <vector>


/* ---- ISS model for fmac_custom (3 x 32-bit words) ---- */
namespace red_fmac_custom {
namespace {
    inline uint32_t float_to_bits(float f) {
        uint32_t b;
        std::memcpy(&b, &f, 4);
        return b;
    }

    inline float bits_to_float(uint32_t b) {
        float f;
        std::memcpy(&f, &b, 4);
        return f;
    }

    inline uint32_t nz_mask(uint32_t x) {
        uint32_t sign = (x | (0u - x)) >> 31;
        return 0u - sign;
    }

    inline uint32_t z_mask(uint32_t x) {
        return ~nz_mask(x);
    }

    inline uint32_t ftz_bits(uint32_t bits) {
        uint32_t exp = (bits >> 23) & 0xFF;
        uint32_t m = z_mask(exp);
        return (bits & ~m) | ((bits & 0x80000000) & m);
    }

    inline uint32_t canon_nan_bits(uint32_t bits) {
        uint32_t exp = (bits >> 23) & 0xFF;
        uint32_t frac = bits & 0x7FFFFF;
        uint32_t is_ff_exp_mask = z_mask(exp ^ 0xFF);
        uint32_t is_frac_nz_mask = nz_mask(frac);
        uint32_t m = is_ff_exp_mask & is_frac_nz_mask;
        return (0x7FC00000 & m) | (bits & ~m);
    }
}

void fmac_custom_iss(const uint32_t in[3], uint32_t out[3]) {
    uint32_t a_bits = ftz_bits(in[0]);
    uint32_t b_bits = ftz_bits(in[1]);
    uint32_t c_bits = ftz_bits(in[2]);

    float a = bits_to_float(a_bits);
    float b = bits_to_float(b_bits);
    float c = bits_to_float(c_bits);

    float p_f = a * b;
    uint32_t p_bits = float_to_bits(p_f);
    p_bits = ftz_bits(p_bits);
    p_bits = canon_nan_bits(p_bits);

    float p = bits_to_float(p_bits);
    float res_f = c + p;
    uint32_t res_bits = float_to_bits(res_f);
    res_bits = ftz_bits(res_bits);
    res_bits = canon_nan_bits(res_bits);

    out[0] = res_bits;
    out[1] = 0;
    out[2] = 0;
}
}



static reg_t red_exec_fmac_custom(processor_t* p, insn_t insn, reg_t pc)
{
  const reg_t src = RS1, dst = RS2;
  uint32_t in[3], out[3];

  for (int i = 0; i < 3; i++)
    in[i] = (uint32_t)MMU.load<uint32_t>(src + 4 * i);
  memset(out, 0, sizeof(out));

  red_fmac_custom::fmac_custom_iss(in, out);

  for (int i = 0; i < 3; i++)
    MMU.store<uint32_t>(dst + 4 * i, out[i]);

  WRITE_RD(0);
  return pc + 4;
}


class red_ext_t : public extension_t
{
 public:
  const char* name() const override { return "red"; }

  std::vector<insn_desc_t> get_instructions(const processor_t &) override {
    return {
      {0x0000002b, 0xfe00707f, red_exec_fmac_custom, red_exec_fmac_custom, red_exec_fmac_custom, red_exec_fmac_custom, red_exec_fmac_custom, red_exec_fmac_custom, red_exec_fmac_custom, red_exec_fmac_custom},
    };
  }

  std::vector<disasm_insn_t*> get_disasms(const processor_t *) override {
    return {
      new disasm_insn_t("fmac_custom", 0x0000002b, 0xfe00707f, {}),
    };
  }
};

REGISTER_EXTENSION(red, []() { static red_ext_t ext; return &ext; })
