
/* Generated by RED (red/iss.py) from ISASpec "CRC_Extensions" — do not edit.
 *
 * One Spike extension holding every designed instruction. Each is a plain
 * R-type in a custom opcode slot: rs1 = &in[words], rs2 = &out[words], rd = 0.
 */
/* libstdc++'s <atomic_wait> reaches for SYS_futex, which spike's own build gets
   transitively; include it up front so this stands alone. */
#include <sys/syscall.h>

/* Every file that uses spike's register macros must first say whether register
   writes go into the commit log. Spike's own instruction bodies define it (0 in
   insn_template.cc, 1 in rocc.cc); 1 keeps --log-commits honest for our
   instructions too. */
#define DECODE_MACRO_USAGE_LOGGED 1

#include "extension.h"
#include "decode_macros.h"
#include "mmu.h"

#include <cstdint>
#include <cstring>
#include <vector>


/* ---- ISS model for crc64_ecma_step (3 x 32-bit words) ---- */
namespace red_crc64_ecma_step {
void crc64_ecma_step_iss(const uint32_t in[3], uint32_t out[3]) {
    uint64_t crc = ((uint64_t)in[1] << 32) | in[0];
    uint32_t data = in[2];
    for (int i = 0; i <= 3; ++i) {
        uint64_t byte = (data >> (i * 8)) & 0xFF;
        crc ^= (byte << 56);
        for (int b = 0; b <= 7; ++b) {
            uint64_t mask = (crc >> 63) ? ~0ULL : 0ULL;
            crc = (crc << 1) ^ (0x42F0E1EBA9EA3693ULL & mask);
        }
    }
    out[0] = (uint32_t)(crc & 0xFFFFFFFF);
    out[1] = (uint32_t)(crc >> 32);
    out[2] = 0;
}
}


/* ---- ISS model for crc32_step (3 x 32-bit words) ---- */
namespace red_crc32_step {
void crc32_step_iss(const uint32_t in[3], uint32_t out[3]) {
    uint32_t crc = in[0];
    for (int w = 0; w <= 1; ++w) {
        uint32_t data = in[w + 1];
        for (int i = 0; i <= 3; ++i) {
            uint32_t byte = (data >> (i * 8)) & 0xFF;
            crc ^= byte;
            for (int b = 0; b <= 7; ++b) {
                uint32_t mask = (crc & 1) ? ~0UL : 0UL;
                crc = (crc >> 1) ^ (0xEDB88320UL & mask);
            }
        }
    }
    out[0] = crc;
    out[1] = 0;
    out[2] = 0;
}
}


/* ---- ISS model for crc16_step (3 x 32-bit words) ---- */
namespace red_crc16_step {
void crc16_step_iss(const uint32_t in[3], uint32_t out[3]) {
    uint32_t crc = in[0] & 0xFFFF;
    for (int w = 0; w <= 1; ++w) {
        uint32_t data = in[w + 1];
        for (int i = 0; i <= 3; ++i) {
            uint32_t byte = (data >> (i * 8)) & 0xFF;
            crc ^= byte;
            for (int b = 0; b <= 7; ++b) {
                uint32_t mask = (crc & 1) ? ~0UL : 0UL;
                crc = (crc >> 1) ^ (0xA001UL & mask);
            }
        }
    }
    out[0] = crc;
    out[1] = 0;
    out[2] = 0;
}
}



static reg_t red_exec_crc64_ecma_step(processor_t* p, insn_t insn, reg_t pc)
{
  const reg_t src = RS1, dst = RS2;
  uint32_t in[3], out[3];

  for (int i = 0; i < 3; i++)
    in[i] = (uint32_t)MMU.load<uint32_t>(src + 4 * i);
  memset(out, 0, sizeof(out));

  red_crc64_ecma_step::crc64_ecma_step_iss(in, out);

  for (int i = 0; i < 3; i++)
    MMU.store<uint32_t>(dst + 4 * i, out[i]);

  WRITE_RD(0);
  return pc + 4;
}


static reg_t red_exec_crc32_step(processor_t* p, insn_t insn, reg_t pc)
{
  const reg_t src = RS1, dst = RS2;
  uint32_t in[3], out[3];

  for (int i = 0; i < 3; i++)
    in[i] = (uint32_t)MMU.load<uint32_t>(src + 4 * i);
  memset(out, 0, sizeof(out));

  red_crc32_step::crc32_step_iss(in, out);

  for (int i = 0; i < 3; i++)
    MMU.store<uint32_t>(dst + 4 * i, out[i]);

  WRITE_RD(0);
  return pc + 4;
}


static reg_t red_exec_crc16_step(processor_t* p, insn_t insn, reg_t pc)
{
  const reg_t src = RS1, dst = RS2;
  uint32_t in[3], out[3];

  for (int i = 0; i < 3; i++)
    in[i] = (uint32_t)MMU.load<uint32_t>(src + 4 * i);
  memset(out, 0, sizeof(out));

  red_crc16_step::crc16_step_iss(in, out);

  for (int i = 0; i < 3; i++)
    MMU.store<uint32_t>(dst + 4 * i, out[i]);

  WRITE_RD(0);
  return pc + 4;
}


class red_ext_t : public extension_t
{
 public:
  const char* name() const override { return "red"; }

  std::vector<insn_desc_t> get_instructions(const processor_t &) override {
    return {
      {0x0000000b, 0xfe00707f, red_exec_crc64_ecma_step, red_exec_crc64_ecma_step, red_exec_crc64_ecma_step, red_exec_crc64_ecma_step, red_exec_crc64_ecma_step, red_exec_crc64_ecma_step, red_exec_crc64_ecma_step, red_exec_crc64_ecma_step},
      {0x0000100b, 0xfe00707f, red_exec_crc32_step, red_exec_crc32_step, red_exec_crc32_step, red_exec_crc32_step, red_exec_crc32_step, red_exec_crc32_step, red_exec_crc32_step, red_exec_crc32_step},
      {0x0000200b, 0xfe00707f, red_exec_crc16_step, red_exec_crc16_step, red_exec_crc16_step, red_exec_crc16_step, red_exec_crc16_step, red_exec_crc16_step, red_exec_crc16_step, red_exec_crc16_step},
    };
  }

  std::vector<disasm_insn_t*> get_disasms(const processor_t *) override {
    return {
      new disasm_insn_t("crc64_ecma_step", 0x0000000b, 0xfe00707f, {}),
      new disasm_insn_t("crc32_step", 0x0000100b, 0xfe00707f, {}),
      new disasm_insn_t("crc16_step", 0x0000200b, 0xfe00707f, {}),
    };
  }
};

REGISTER_EXTENSION(red, []() { static red_ext_t ext; return &ext; })
