
/* Generated by RED (red/iss.py): native reference run of secp256r1.mult's c_model.
 * Prints one 32-bit word per line, lowercase hex — the exact format Spike's
 * +signature dump uses, so the two are compared line by line. */
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define RED_WORDS   16
#define RED_NVEC    100000
#define RED_NCORNER 4
#define RED_BLOCK   1024

/* ---- designer-supplied C reference model ---- */
#include <stdint.h>

void secp256r1_mult_model(const uint32_t in[16], uint32_t out[16]) {
    uint32_t r0 = 0, r1 = 0, r2 = 0;
    
    for (int k = 0; k < 8; ++k) {
        for (int i = 0; i <= k; ++i) {
            uint64_t p = (uint64_t)in[i] * in[8 + k - i];
            uint64_t r01 = ((uint64_t)r1 << 32) | r0;
            r01 += p;
            r2 += (r01 < p);
            r1 = r01 >> 32;
            r0 = (uint32_t)r01;
        }
        out[k] = r0;
        r0 = r1;
        r1 = r2;
        r2 = 0;
    }
    for (int k = 8; k < 15; ++k) {
        for (int i = (k + 1) - 8; i < 8; ++i) {
            uint64_t p = (uint64_t)in[i] * in[8 + k - i];
            uint64_t r01 = ((uint64_t)r1 << 32) | r0;
            r01 += p;
            r2 += (r01 < p);
            r1 = r01 >> 32;
            r0 = (uint32_t)r01;
        }
        out[k] = r0;
        r0 = r1;
        r1 = r2;
        r2 = 0;
    }
    out[15] = r0;
}
/* ---- end model ---- */


static uint32_t red_xs32(uint32_t *s) {
  uint32_t x = *s;
  x ^= x << 13; x ^= x >> 17; x ^= x << 5;
  return *s = x;
}

static const uint32_t RED_CORNERS[RED_NCORNER] = { 0x00000000u, 0xffffffffu, 0xaaaaaaaau, 0x55555555u };

/* Vector i: the first RED_NCORNER are uniform corner patterns, the rest are
   drawn from the PRNG. The PRNG is advanced only by the random vectors, so
   both harnesses stay in lockstep. */
static void red_fill(long i, uint32_t *seed, uint32_t *in) {
  int w;
  if (i < RED_NCORNER) {
    for (w = 0; w < RED_WORDS; w++) in[w] = RED_CORNERS[i];
  } else {
    for (w = 0; w < RED_WORDS; w++) in[w] = red_xs32(seed);
  }
}

static uint32_t red_hash(uint32_t h, const uint32_t *v, int n) {
  int w, b;
  for (w = 0; w < n; w++)
    for (b = 0; b < 4; b++) {
      h ^= (v[w] >> (8 * b)) & 0xffu;
      h *= 16777619u;
    }
  return h;
}


int main(void) {
  uint32_t in[RED_WORDS], out[RED_WORDS];
  uint32_t seed = 0xc0ffeeu, h = 2166136261u;
  long i, w, blk = 0;
  (void)blk;

  for (i = 0; i < RED_NVEC; i++) {
    red_fill(i, &seed, in);
    memset(out, 0, sizeof out);
    secp256r1_mult_model(in, out);
    h = red_hash(h, out, RED_WORDS);
    if ((i + 1) % RED_BLOCK == 0 || i + 1 == RED_NVEC) {
      printf("%08x\n", h);
    }
  }
  return 0;
}
