
/* Generated by RED (red/iss.py): bare-metal rv32 run of secp256r1.mult on Spike.
 *
 * Executes the custom instruction itself — encoding, register operands and
 * memory traffic all go through the simulator — and leaves its results in the
 * .signature region, which Spike writes out with +signature. Freestanding: no
 * libc, no crt0, no HTIF console; the only host interaction is the exit word. */
#include <stdint.h>

#define RED_WORDS   16
#define RED_NVEC    100000
#define RED_NCORNER 4
#define RED_BLOCK   1024

/* fesvr finds these by symbol name; writing 1 to tohost exits the simulation.
   On rv32 that is two 32-bit stores, and both orderings are safe here: the
   intermediate value is either 0 (no request) or 1 (the exit request). */
volatile uint64_t tohost   __attribute__((section(".htif"), aligned(8)));
volatile uint64_t fromhost __attribute__((section(".htif"), aligned(8)));

/* Bracketed by begin_signature/end_signature in the linker script. Initialised
   to a sentinel so the section is PROGBITS and an entry the program never wrote
   is obvious in the dump rather than reading as a plausible zero. */
volatile uint32_t red_sig[98] __attribute__((section(".signature"), used))
  = { [0 ... 97] = 0xdeadbeefu };

static uint32_t red_in[RED_WORDS], red_out[RED_WORDS];


static uint32_t red_xs32(uint32_t *s) {
  uint32_t x = *s;
  x ^= x << 13; x ^= x >> 17; x ^= x << 5;
  return *s = x;
}

static const uint32_t RED_CORNERS[RED_NCORNER] = { 0x00000000u, 0xffffffffu, 0xaaaaaaaau, 0x55555555u };

/* Vector i: the first RED_NCORNER are uniform corner patterns, the rest are
   drawn from the PRNG. The PRNG is advanced only by the random vectors, so
   both harnesses stay in lockstep. */
static void red_fill(long i, uint32_t *seed, uint32_t *in) {
  int w;
  if (i < RED_NCORNER) {
    for (w = 0; w < RED_WORDS; w++) in[w] = RED_CORNERS[i];
  } else {
    for (w = 0; w < RED_WORDS; w++) in[w] = red_xs32(seed);
  }
}

static uint32_t red_hash(uint32_t h, const uint32_t *v, int n) {
  int w, b;
  for (w = 0; w < n; w++)
    for (b = 0; b < 4; b++) {
      h ^= (v[w] >> (8 * b)) & 0xffu;
      h *= 16777619u;
    }
  return h;
}


int main(void) {
  uint32_t seed = 0xc0ffeeu, h = 2166136261u;
  long i, w;
  long blk = 0;

  for (i = 0; i < RED_NVEC; i++) {
    red_fill(i, &seed, red_in);
    for (w = 0; w < RED_WORDS; w++) red_out[w] = 0;
    {
      uint32_t rd_val;
      const uint32_t *src = red_in;
      uint32_t *dst = red_out;
      /* <mnemonic> rd, rs1, rs2  with rs1 = &in, rs2 = &out */
      __asm__ __volatile__(".insn r 0x0b, 0x0, 0x01, %0, %1, %2"
                           : "=r"(rd_val) : "r"(src), "r"(dst) : "memory");
      (void)rd_val;
    }
    h = red_hash(h, (const uint32_t *)red_out, RED_WORDS);
    if ((i + 1) % RED_BLOCK == 0 || i + 1 == RED_NVEC) {
      red_sig[blk] = h; blk++;
    }
  }

  tohost = 1;          /* exit(0) */
  for (;;) { }
}

void _start(void) __attribute__((naked, section(".text.init")));
void _start(void) {
  __asm__ __volatile__(
    "la sp, _stack_top\n"
    "call main\n"
    "la t0, tohost\n"
    "li t1, 1\n"
    "sw t1, 0(t0)\n"
    "1: j 1b\n");
}
