
/* Generated by RED (red/iss.py): native reference run of fmac_custom's c_model.
 * Prints one 32-bit word per line, lowercase hex — the exact format Spike's
 * +signature dump uses, so the two are compared line by line. */
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define RED_WORDS   3
#define RED_NVEC    100000
#define RED_NCORNER 4
#define RED_BLOCK   1024

/* ---- designer-supplied C reference model ---- */
#include <stdint.h>
#include <string.h>

static uint32_t ftz_u32(uint32_t bits) {
    uint32_t exp = (bits >> 23) & 0xFF;
    uint32_t exp_is_zero = (exp - 1) >> 31;
    uint32_t mask = 0xFFFFFFFF ^ (exp_is_zero * 0x7FFFFFFF);
    return bits & mask;
}

static float ftz_f32(float x) {
    uint32_t bits;
    memcpy(&bits, &x, 4);
    bits = ftz_u32(bits);
    memcpy(&x, &bits, 4);
    return x;
}

static uint32_t canon_nan(float x) {
    uint32_t bits;
    memcpy(&bits, &x, 4);
    uint32_t exp = (bits >> 23) & 0xFF;
    uint32_t frac = bits & 0x7FFFFF;
    uint32_t is_nan = (exp == 0xFF) & (frac != 0);
    uint32_t m = (uint32_t)0 - is_nan;
    return (0x7FC00000 & m) | (bits & ~m);
}

void fmac_custom_model(const uint32_t in[3], uint32_t out[3]) {
    float a, b, c;
    uint32_t tmp;

    tmp = ftz_u32(in[0]); memcpy(&a, &tmp, 4);
    tmp = ftz_u32(in[1]); memcpy(&b, &tmp, 4);
    tmp = ftz_u32(in[2]); memcpy(&c, &tmp, 4);

    float p = ftz_f32(a * b);
    uint32_t p_bits = canon_nan(p);
    memcpy(&p, &p_bits, 4);

    float s = ftz_f32(c + p);
    uint32_t s_bits = canon_nan(s);

    out[0] = ftz_u32(s_bits);
    out[1] = 0;
    out[2] = 0;
}
/* ---- end model ---- */


static uint32_t red_xs32(uint32_t *s) {
  uint32_t x = *s;
  x ^= x << 13; x ^= x >> 17; x ^= x << 5;
  return *s = x;
}

static const uint32_t RED_CORNERS[RED_NCORNER] = { 0x00000000u, 0xffffffffu, 0xaaaaaaaau, 0x55555555u };

/* Vector i: the first RED_NCORNER are uniform corner patterns, the rest are
   drawn from the PRNG. The PRNG is advanced only by the random vectors, so
   both harnesses stay in lockstep. */
static void red_fill(long i, uint32_t *seed, uint32_t *in) {
  int w;
  if (i < RED_NCORNER) {
    for (w = 0; w < RED_WORDS; w++) in[w] = RED_CORNERS[i];
  } else {
    for (w = 0; w < RED_WORDS; w++) in[w] = red_xs32(seed);
  }
}

static uint32_t red_hash(uint32_t h, const uint32_t *v, int n) {
  int w, b;
  for (w = 0; w < n; w++)
    for (b = 0; b < 4; b++) {
      h ^= (v[w] >> (8 * b)) & 0xffu;
      h *= 16777619u;
    }
  return h;
}


int main(void) {
  uint32_t in[RED_WORDS], out[RED_WORDS];
  uint32_t seed = 0xc0ffeeu, h = 2166136261u;
  long i, w, blk = 0;
  (void)blk;

  for (i = 0; i < RED_NVEC; i++) {
    red_fill(i, &seed, in);
    memset(out, 0, sizeof out);
    fmac_custom_model(in, out);
    h = red_hash(h, out, RED_WORDS);
    if ((i + 1) % RED_BLOCK == 0 || i + 1 == RED_NVEC) {
      printf("%08x\n", h);
    }
  }
  return 0;
}
