
/* Generated by RED (red/iss.py) from ISASpec "CRC_Accel" — do not edit.
 *
 * One Spike extension holding every designed instruction. Each is a plain
 * R-type in a custom opcode slot: rs1 = &in[words], rs2 = &out[words], rd = 0.
 */
/* libstdc++'s <atomic_wait> reaches for SYS_futex, which spike's own build gets
   transitively; include it up front so this stands alone. */
#include <sys/syscall.h>

/* Every file that uses spike's register macros must first say whether register
   writes go into the commit log. Spike's own instruction bodies define it (0 in
   insn_template.cc, 1 in rocc.cc); 1 keeps --log-commits honest for our
   instructions too. */
#define DECODE_MACRO_USAGE_LOGGED 1

#include "extension.h"
#include "decode_macros.h"
#include "mmu.h"

#include <cstdint>
#include <cstring>
#include <vector>


/* ---- ISS model for crc64_ecma_step32b (3 x 32-bit words) ---- */
namespace red_crc64_ecma_step32b {
void crc64_ecma_step32b_iss(const uint32_t in[3], uint32_t out[3]) {
    uint64_t crc = ((uint64_t)in[1] << 32) | in[0];
    uint32_t data = in[2];
    for(int i=0; i<4; i++) {
        uint8_t val = (data >> (i*8)) & 0xFF;
        uint64_t c = crc ^ ((uint64_t)val << 56);
        for(int j=0; j<8; j++) {
            uint64_t mask = (uint64_t)0 - (c >> 63);
            c = ((c << 1) & 0xFFFFFFFFFFFFFFFFull) ^ (0x42F0E1EBA9EA3693ull & mask);
        }
        crc = c;
    }
    out[0] = (uint32_t)crc;
    out[1] = (uint32_t)(crc >> 32);
    out[2] = 0;
}
}


/* ---- ISS model for crcccitt_step32b (2 x 32-bit words) ---- */
namespace red_crcccitt_step32b {
void crcccitt_step32b_iss(const uint32_t in[2], uint32_t out[2]) {
    uint16_t crc = (uint16_t)in[0];
    uint32_t data = in[1];
    for(int i=0; i<4; i++) {
        uint8_t val = (data >> (i*8)) & 0xFF;
        uint16_t c = crc ^ ((uint16_t)val << 8);
        for(int j=0; j<8; j++) {
            uint16_t mask = (uint16_t)0 - (c >> 15);
            c = ((c << 1) & 0xFFFF) ^ (0x1021 & mask);
        }
        crc = c;
    }
    out[0] = crc;
    out[1] = 0;
}
}


/* ---- ISS model for crc32_step32b (2 x 32-bit words) ---- */
namespace red_crc32_step32b {
void crc32_step32b_iss(const uint32_t in[2], uint32_t out[2]) {
    uint32_t crc = in[0];
    uint32_t data = in[1];
    for(int i=0; i<4; i++) {
        uint8_t val = (data >> (i*8)) & 0xFF;
        uint32_t c = crc ^ val;
        for(int j=0; j<8; j++) {
            uint32_t mask = (uint32_t)0 - (c & 1);
            c = (c >> 1) ^ (0xEDB88320ul & mask);
        }
        crc = c;
    }
    out[0] = crc;
    out[1] = 0;
}
}


/* ---- ISS model for crc16_step32b (2 x 32-bit words) ---- */
namespace red_crc16_step32b {
void crc16_step32b_iss(const uint32_t in[2], uint32_t out[2]) {
    uint16_t crc = (uint16_t)in[0];
    uint32_t data = in[1];
    for(int i=0; i<4; i++) {
        uint8_t val = (data >> (i*8)) & 0xFF;
        uint16_t c = crc ^ val;
        for(int j=0; j<8; j++) {
            uint16_t mask = (uint16_t)0 - (c & 1);
            c = (c >> 1) ^ (0xA001 & mask);
        }
        crc = c;
    }
    out[0] = crc;
    out[1] = 0;
}
}


/* ---- ISS model for crcdnp_step32b (2 x 32-bit words) ---- */
namespace red_crcdnp_step32b {
void crcdnp_step32b_iss(const uint32_t in[2], uint32_t out[2]) {
    uint16_t crc = (uint16_t)in[0];
    uint32_t data = in[1];
    for(int i=0; i<4; i++) {
        uint8_t val = (data >> (i*8)) & 0xFF;
        uint16_t c = crc ^ val;
        for(int j=0; j<8; j++) {
            uint16_t mask = (uint16_t)0 - (c & 1);
            c = (c >> 1) ^ (0xA6BC & mask);
        }
        crc = c;
    }
    out[0] = crc;
    out[1] = 0;
}
}


/* ---- ISS model for crc8_step32b (2 x 32-bit words) ---- */
namespace red_crc8_step32b {
void crc8_step32b_iss(const uint32_t in[2], uint32_t out[2]) {
    uint8_t crc = (uint8_t)in[0];
    uint32_t data = in[1];
    for(int i=0; i<4; i++) {
        uint8_t val = (data >> (i*8)) & 0xFF;
        uint8_t c = crc ^ val;
        for(int j=0; j<8; j++) {
            uint8_t mask = (uint8_t)0 - (c >> 7);
            c = ((c << 1) & 0xFF) ^ (0x31 & mask);
        }
        crc = c;
    }
    out[0] = crc;
    out[1] = 0;
}
}



static reg_t red_exec_crc64_ecma_step32b(processor_t* p, insn_t insn, reg_t pc)
{
  const reg_t src = RS1, dst = RS2;
  uint32_t in[3], out[3];

  for (int i = 0; i < 3; i++)
    in[i] = (uint32_t)MMU.load<uint32_t>(src + 4 * i);
  memset(out, 0, sizeof(out));

  red_crc64_ecma_step32b::crc64_ecma_step32b_iss(in, out);

  for (int i = 0; i < 3; i++)
    MMU.store<uint32_t>(dst + 4 * i, out[i]);

  WRITE_RD(0);
  return pc + 4;
}


static reg_t red_exec_crcccitt_step32b(processor_t* p, insn_t insn, reg_t pc)
{
  const reg_t src = RS1, dst = RS2;
  uint32_t in[2], out[2];

  for (int i = 0; i < 2; i++)
    in[i] = (uint32_t)MMU.load<uint32_t>(src + 4 * i);
  memset(out, 0, sizeof(out));

  red_crcccitt_step32b::crcccitt_step32b_iss(in, out);

  for (int i = 0; i < 2; i++)
    MMU.store<uint32_t>(dst + 4 * i, out[i]);

  WRITE_RD(0);
  return pc + 4;
}


static reg_t red_exec_crc32_step32b(processor_t* p, insn_t insn, reg_t pc)
{
  const reg_t src = RS1, dst = RS2;
  uint32_t in[2], out[2];

  for (int i = 0; i < 2; i++)
    in[i] = (uint32_t)MMU.load<uint32_t>(src + 4 * i);
  memset(out, 0, sizeof(out));

  red_crc32_step32b::crc32_step32b_iss(in, out);

  for (int i = 0; i < 2; i++)
    MMU.store<uint32_t>(dst + 4 * i, out[i]);

  WRITE_RD(0);
  return pc + 4;
}


static reg_t red_exec_crc16_step32b(processor_t* p, insn_t insn, reg_t pc)
{
  const reg_t src = RS1, dst = RS2;
  uint32_t in[2], out[2];

  for (int i = 0; i < 2; i++)
    in[i] = (uint32_t)MMU.load<uint32_t>(src + 4 * i);
  memset(out, 0, sizeof(out));

  red_crc16_step32b::crc16_step32b_iss(in, out);

  for (int i = 0; i < 2; i++)
    MMU.store<uint32_t>(dst + 4 * i, out[i]);

  WRITE_RD(0);
  return pc + 4;
}


static reg_t red_exec_crcdnp_step32b(processor_t* p, insn_t insn, reg_t pc)
{
  const reg_t src = RS1, dst = RS2;
  uint32_t in[2], out[2];

  for (int i = 0; i < 2; i++)
    in[i] = (uint32_t)MMU.load<uint32_t>(src + 4 * i);
  memset(out, 0, sizeof(out));

  red_crcdnp_step32b::crcdnp_step32b_iss(in, out);

  for (int i = 0; i < 2; i++)
    MMU.store<uint32_t>(dst + 4 * i, out[i]);

  WRITE_RD(0);
  return pc + 4;
}


static reg_t red_exec_crc8_step32b(processor_t* p, insn_t insn, reg_t pc)
{
  const reg_t src = RS1, dst = RS2;
  uint32_t in[2], out[2];

  for (int i = 0; i < 2; i++)
    in[i] = (uint32_t)MMU.load<uint32_t>(src + 4 * i);
  memset(out, 0, sizeof(out));

  red_crc8_step32b::crc8_step32b_iss(in, out);

  for (int i = 0; i < 2; i++)
    MMU.store<uint32_t>(dst + 4 * i, out[i]);

  WRITE_RD(0);
  return pc + 4;
}


class red_ext_t : public extension_t
{
 public:
  const char* name() const override { return "red"; }

  std::vector<insn_desc_t> get_instructions(const processor_t &) override {
    return {
      {0x0000000b, 0xfe00707f, red_exec_crc64_ecma_step32b, red_exec_crc64_ecma_step32b, red_exec_crc64_ecma_step32b, red_exec_crc64_ecma_step32b, red_exec_crc64_ecma_step32b, red_exec_crc64_ecma_step32b, red_exec_crc64_ecma_step32b, red_exec_crc64_ecma_step32b},
      {0x0000100b, 0xfe00707f, red_exec_crcccitt_step32b, red_exec_crcccitt_step32b, red_exec_crcccitt_step32b, red_exec_crcccitt_step32b, red_exec_crcccitt_step32b, red_exec_crcccitt_step32b, red_exec_crcccitt_step32b, red_exec_crcccitt_step32b},
      {0x0000200b, 0xfe00707f, red_exec_crc32_step32b, red_exec_crc32_step32b, red_exec_crc32_step32b, red_exec_crc32_step32b, red_exec_crc32_step32b, red_exec_crc32_step32b, red_exec_crc32_step32b, red_exec_crc32_step32b},
      {0x0000300b, 0xfe00707f, red_exec_crc16_step32b, red_exec_crc16_step32b, red_exec_crc16_step32b, red_exec_crc16_step32b, red_exec_crc16_step32b, red_exec_crc16_step32b, red_exec_crc16_step32b, red_exec_crc16_step32b},
      {0x0000400b, 0xfe00707f, red_exec_crcdnp_step32b, red_exec_crcdnp_step32b, red_exec_crcdnp_step32b, red_exec_crcdnp_step32b, red_exec_crcdnp_step32b, red_exec_crcdnp_step32b, red_exec_crcdnp_step32b, red_exec_crcdnp_step32b},
      {0x0000500b, 0xfe00707f, red_exec_crc8_step32b, red_exec_crc8_step32b, red_exec_crc8_step32b, red_exec_crc8_step32b, red_exec_crc8_step32b, red_exec_crc8_step32b, red_exec_crc8_step32b, red_exec_crc8_step32b},
    };
  }

  std::vector<disasm_insn_t*> get_disasms(const processor_t *) override {
    return {
      new disasm_insn_t("crc64_ecma_step32b", 0x0000000b, 0xfe00707f, {}),
      new disasm_insn_t("crcccitt_step32b", 0x0000100b, 0xfe00707f, {}),
      new disasm_insn_t("crc32_step32b", 0x0000200b, 0xfe00707f, {}),
      new disasm_insn_t("crc16_step32b", 0x0000300b, 0xfe00707f, {}),
      new disasm_insn_t("crcdnp_step32b", 0x0000400b, 0xfe00707f, {}),
      new disasm_insn_t("crc8_step32b", 0x0000500b, 0xfe00707f, {}),
    };
  }
};

REGISTER_EXTENSION(red, []() { static red_ext_t ext; return &ext; })
