
/* Generated by RED (red/iss.py) from ISASpec "MicroECC secp256r1 Extension" — do not edit.
 *
 * One Spike extension holding every designed instruction. Each is a plain
 * R-type in a custom opcode slot: rs1 = &in[words], rs2 = &out[words], rd = 0.
 */
/* libstdc++'s <atomic_wait> reaches for SYS_futex, which spike's own build gets
   transitively; include it up front so this stands alone. */
#include <sys/syscall.h>

/* Every file that uses spike's register macros must first say whether register
   writes go into the commit log. Spike's own instruction bodies define it (0 in
   insn_template.cc, 1 in rocc.cc); 1 keeps --log-commits honest for our
   instructions too. */
#define DECODE_MACRO_USAGE_LOGGED 1

#include "extension.h"
#include "decode_macros.h"
#include "mmu.h"

#include <cstdint>
#include <cstring>
#include <vector>


/* ---- ISS model for secp256r1.mult (16 x 32-bit words) ---- */
namespace red_secp256r1_mult {
void secp256r1_mult_iss(const uint32_t in[16], uint32_t out[16]) {
    for (int i = 0; i < 16; ++i) {
        out[i] = 0;
    }
    for (int i = 0; i < 8; ++i) {
        uint64_t carry = 0;
        for (int j = 0; j < 8; ++j) {
            uint64_t prod = (uint64_t)in[i] * in[8 + j] + out[i + j] + carry;
            out[i + j] = (uint32_t)prod;
            carry = prod >> 32;
        }
        out[i + 8] = (uint32_t)carry;
    }
}
}



static reg_t red_exec_secp256r1_mult(processor_t* p, insn_t insn, reg_t pc)
{
  const reg_t src = RS1, dst = RS2;
  uint32_t in[16], out[16];

  for (int i = 0; i < 16; i++)
    in[i] = (uint32_t)MMU.load<uint32_t>(src + 4 * i);
  memset(out, 0, sizeof(out));

  red_secp256r1_mult::secp256r1_mult_iss(in, out);

  for (int i = 0; i < 16; i++)
    MMU.store<uint32_t>(dst + 4 * i, out[i]);

  WRITE_RD(0);
  return pc + 4;
}


class red_ext_t : public extension_t
{
 public:
  const char* name() const override { return "red"; }

  std::vector<insn_desc_t> get_instructions(const processor_t &) override {
    return {
      {0x0200000b, 0xfe00707f, red_exec_secp256r1_mult, red_exec_secp256r1_mult, red_exec_secp256r1_mult, red_exec_secp256r1_mult, red_exec_secp256r1_mult, red_exec_secp256r1_mult, red_exec_secp256r1_mult, red_exec_secp256r1_mult},
    };
  }

  std::vector<disasm_insn_t*> get_disasms(const processor_t *) override {
    return {
      new disasm_insn_t("secp256r1.mult", 0x0200000b, 0xfe00707f, {}),
    };
  }
};

REGISTER_EXTENSION(red, []() { static red_ext_t ext; return &ext; })
